create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'طالب',
  grade text not null default 'الثانوية العامة',
  daily_goal_minutes integer not null default 180,
  points integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#6D4AFF'
);
insert into public.subjects(name,color) values
('الرياضيات','#20B76B'),('الفيزياء','#2F80ED'),('الكيمياء','#8B5CF6'),('العربي','#F97316'),('الإنجليزي','#F59E0B')
on conflict (name) do nothing;

create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id bigint references public.subjects(id),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_minutes integer not null default 0,
  completed boolean not null default false
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  subject_id bigint references public.subjects(id), title text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question text not null, options jsonb not null, correct_index integer not null
);
create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  score integer not null default 0, total integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  code text unique not null, title text not null, description text not null,
  icon text not null default '🏆'
);
insert into public.badges(code,title,description,icon) values
('first_session','أول جلسة مذاكرة','ابدأ أول جلسة مذاكرة','⭐'),
('streak_7','أسبوع متتالي','ذاكر 7 أيام متتالية','🔥'),
('hours_10','10 ساعات','أكمل 10 ساعات مذاكرة','⏱️'),
('quiz_10','اختبار محترف','أكمل 10 اختبارات','🧠'),
('points_1000','جامع النقاط','اجمع 1000 نقطة','🏆')
on conflict (code) do nothing;
create table if not exists public.user_badges (
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_id bigint not null references public.badges(id) on delete cascade,
  earned_at timestamptz not null default now(), primary key(user_id,badge_id)
);

alter table public.profiles enable row level security;
alter table public.study_sessions enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.subjects enable row level security;
alter table public.quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;

create policy "profile own" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "sessions own" on public.study_sessions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "attempts own" on public.quiz_attempts for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "subjects readable" on public.subjects for select using (true);
create policy "quizzes readable" on public.quizzes for select using (true);
create policy "questions readable" on public.quiz_questions for select using (true);
create policy "badges readable" on public.badges for select using (true);
create policy "user badges own" on public.user_badges for select using (auth.uid()=user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name','طالب'));
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Initial five-question quiz
DO $$ declare s bigint; q bigint; begin
 select id into s from public.subjects where name='الفيزياء' limit 1;
 if not exists(select 1 from public.quizzes where title='اختبار فيزياء سريع') then
  insert into public.quizzes(subject_id,title) values(s,'اختبار فيزياء سريع') returning id into q;
  insert into public.quiz_questions(quiz_id,question,options,correct_index) values
  (q,'أي مما يلي وحدة لقياس الجهد الكهربائي?','["الفولت","الأوم","الواط","الأمبير"]',0),
  (q,'ما الجهاز المستخدم لقياس شدة التيار?','["الفولتميتر","الأميتر","البارومتر","الترمومتر"]',1),
  (q,'أي كمية كهربائية تقاس بالأوم?','["المقاومة","القدرة","الشحنة","الطاقة"]',0),
  (q,'ما الرمز الشائع للمقاومة الكهربائية?','["R","V","I","P"]',0),
  (q,'أي مما يلي مصدر للطاقة الكهربائية?','["البطارية","المصباح","المفتاح","السلك"]',0);
 end if;
end $$;
